# .rustfmt.toml — для nightly

blank_lines_upper_bound = 0
blank_lines_lower_bound = 0

# fn_single_line = true
# reorder_impl_items = false

# format_code_in_doc_comments = false

max_width = 100
tab_spaces = 4
hard_tabs = false
trailing_comma = "Vertical"
wrap_match_arms = true
match_block_trailing_comma = false
chain_indent = "Block"
struct_field_align_threshold = 0