max_width = 100
tab_spaces = 4
hard_tabs = false
blank_lines_upper_bound = 0
blank_lines_lower_bound = 0
trailing_comma = "Vertical"
wrap_match_arms = true
match_block_trailing_comma = false
chain_indent = "Block"
struct_field_align_threshold = 0
format_code_in_doc_comments = true

# fn_single_line = true
# reorder_impl_items = false