//! Tests for format_* methods generated by impl_format_numeric! and impl_format_string! macros.
//!
//! These tests verify that the macro-generated methods work correctly with real GpuInfo instances.

use crate::vendor::Vendor;
use crate::GpuInfo;

/// Test format methods with all fields set to None (unknown GPU)
#[test]
fn test_format_methods_with_unknown_gpu() {
    let gpu = GpuInfo::unknown();

    // Numeric f32 fields should return 0.0
    assert_eq!(gpu.format_temperature(), 0.0);
    assert_eq!(gpu.format_utilization(), 0.0);
    assert_eq!(gpu.format_power_usage(), 0.0);
    assert_eq!(gpu.format_memory_util(), 0.0);
    assert_eq!(gpu.format_power_limit(), 0.0);

    // Numeric u32 fields should return 0
    assert_eq!(gpu.format_core_clock(), 0);
    assert_eq!(gpu.format_memory_clock(), 0);
    assert_eq!(gpu.format_memory_total(), 0);
    assert_eq!(gpu.format_max_clock_speed(), 0);

    // String fields should return default strings
    assert_eq!(gpu.format_name_gpu(), "Unknown GPU");
    assert_eq!(gpu.format_driver_version(), "Unknown Driver Version");

    // Active status (custom logic, not macro-generated)
    assert_eq!(gpu.format_active(), "Inactive");
}

/// Test format methods with all fields populated
#[test]
fn test_format_methods_with_populated_gpu() {
    let gpu = GpuInfo::builder()
        .vendor(Vendor::Nvidia)
        .name("NVIDIA GeForce RTX 4090")
        .temperature(65.5)
        .utilization(85.0)
        .power_usage(350.0)
        .core_clock(2520)
        .memory_util(45.5)
        .memory_clock(10501)
        .power_limit(450.0)
        .memory_total(24)
        .max_clock_speed(2610)
        .driver_version("545.92")
        .active(true)
        .build();

    // Numeric f32 fields
    assert_eq!(gpu.format_temperature(), 65.5);
    assert_eq!(gpu.format_utilization(), 85.0);
    assert_eq!(gpu.format_power_usage(), 350.0);
    assert_eq!(gpu.format_memory_util(), 45.5);
    assert_eq!(gpu.format_power_limit(), 450.0);

    // Numeric u32 fields
    assert_eq!(gpu.format_core_clock(), 2520);
    assert_eq!(gpu.format_memory_clock(), 10501);
    assert_eq!(gpu.format_memory_total(), 24);
    assert_eq!(gpu.format_max_clock_speed(), 2610);

    // String fields
    assert_eq!(gpu.format_name_gpu(), "NVIDIA GeForce RTX 4090");
    assert_eq!(gpu.format_driver_version(), "545.92");

    // Active status
    assert_eq!(gpu.format_active(), "Active");
}

/// Test format methods with partial data (some fields None, some populated)
#[test]
fn test_format_methods_with_partial_data() {
    let gpu = GpuInfo::builder()
        .vendor(Vendor::Amd)
        .name("AMD Radeon RX 7900 XTX")
        .temperature(72.0)
        // utilization is None
        .power_usage(300.0)
        // core_clock is None
        .memory_util(60.0)
        // memory_clock is None
        .active(false)
        .build();

    // Populated fields return their values
    assert_eq!(gpu.format_name_gpu(), "AMD Radeon RX 7900 XTX");
    assert_eq!(gpu.format_temperature(), 72.0);
    assert_eq!(gpu.format_power_usage(), 300.0);
    assert_eq!(gpu.format_memory_util(), 60.0);

    // None fields return defaults
    assert_eq!(gpu.format_utilization(), 0.0);
    assert_eq!(gpu.format_core_clock(), 0);
    assert_eq!(gpu.format_memory_clock(), 0);
    assert_eq!(gpu.format_memory_total(), 0);
    assert_eq!(gpu.format_max_clock_speed(), 0);
    assert_eq!(gpu.format_power_limit(), 0.0);
    assert_eq!(gpu.format_driver_version(), "Unknown Driver Version");

    // Active is false
    assert_eq!(gpu.format_active(), "Inactive");
}

/// Test format_active with different states
#[test]
fn test_format_active_states() {
    // Active = Some(true)
    let gpu_active = GpuInfo::builder().active(true).build();
    assert_eq!(gpu_active.format_active(), "Active");

    // Active = Some(false)
    let gpu_inactive = GpuInfo::builder().active(false).build();
    assert_eq!(gpu_inactive.format_active(), "Inactive");

    // Active = None (unknown GPU)
    let gpu_unknown = GpuInfo::unknown();
    assert_eq!(gpu_unknown.format_active(), "Inactive");
}

/// Test format methods with edge case values
#[test]
fn test_format_methods_edge_cases() {
    // Zero values
    let gpu_zeros = GpuInfo::builder()
        .temperature(0.0)
        .utilization(0.0)
        .power_usage(0.0)
        .core_clock(0)
        .memory_clock(0)
        .memory_total(0)
        .build();

    assert_eq!(gpu_zeros.format_temperature(), 0.0);
    assert_eq!(gpu_zeros.format_utilization(), 0.0);
    assert_eq!(gpu_zeros.format_power_usage(), 0.0);
    assert_eq!(gpu_zeros.format_core_clock(), 0);
    assert_eq!(gpu_zeros.format_memory_clock(), 0);
    assert_eq!(gpu_zeros.format_memory_total(), 0);

    // Maximum reasonable values
    let gpu_max = GpuInfo::builder()
        .temperature(100.0)
        .utilization(100.0)
        .power_usage(1000.0)
        .core_clock(5000)
        .memory_clock(20000)
        .memory_total(128)
        .max_clock_speed(5000)
        .power_limit(1000.0)
        .build();

    assert_eq!(gpu_max.format_temperature(), 100.0);
    assert_eq!(gpu_max.format_utilization(), 100.0);
    assert_eq!(gpu_max.format_power_usage(), 1000.0);
    assert_eq!(gpu_max.format_core_clock(), 5000);
    assert_eq!(gpu_max.format_memory_clock(), 20000);
    assert_eq!(gpu_max.format_memory_total(), 128);
    assert_eq!(gpu_max.format_max_clock_speed(), 5000);
    assert_eq!(gpu_max.format_power_limit(), 1000.0);
}

/// Test format methods with empty string values
#[test]
fn test_format_methods_empty_strings() {
    let gpu = GpuInfo::builder().name("").driver_version("").build();

    // Empty strings are still valid values, not defaults
    assert_eq!(gpu.format_name_gpu(), "");
    assert_eq!(gpu.format_driver_version(), "");
}

/// Test format methods with special characters in strings
#[test]
fn test_format_methods_special_characters() {
    let gpu = GpuInfo::builder()
        .name("NVIDIA GeForce RTX 4090 (TM)")
        .driver_version("545.92.01-beta")
        .build();

    assert_eq!(gpu.format_name_gpu(), "NVIDIA GeForce RTX 4090 (TM)");
    assert_eq!(gpu.format_driver_version(), "545.92.01-beta");
}

/// Test format methods with floating point precision
#[test]
fn test_format_methods_float_precision() {
    let gpu = GpuInfo::builder()
        .temperature(65.123)
        .utilization(99.999)
        .power_usage(350.5)
        .memory_util(45.123)
        .power_limit(450.0)
        .build();

    // Values should be returned as-is (no rounding in format methods)
    assert!((gpu.format_temperature() - 65.123).abs() < 0.001);
    assert!((gpu.format_utilization() - 99.999).abs() < 0.001);
    assert!((gpu.format_power_usage() - 350.5).abs() < 0.001);
    assert!((gpu.format_memory_util() - 45.123).abs() < 0.001);
    assert!((gpu.format_power_limit() - 450.0).abs() < 0.001);
}

/// Test that format methods work correctly with Intel GPU type
#[test]
fn test_format_methods_intel_gpu() {
    use crate::vendor::IntelGpuType;

    let gpu = GpuInfo::builder()
        .vendor(Vendor::Intel(IntelGpuType::Integrated))
        .name("Intel UHD Graphics 770")
        .temperature(55.0)
        .utilization(30.0)
        .memory_total(1)
        .driver_version("31.0.101.4502")
        .active(true)
        .build();

    assert_eq!(gpu.format_name_gpu(), "Intel UHD Graphics 770");
    assert_eq!(gpu.format_temperature(), 55.0);
    assert_eq!(gpu.format_utilization(), 30.0);
    assert_eq!(gpu.format_memory_total(), 1);
    assert_eq!(gpu.format_driver_version(), "31.0.101.4502");
    assert_eq!(gpu.format_active(), "Active");
}

/// Test format methods consistency with getter methods
#[test]
fn test_format_methods_consistency_with_getters() {
    let gpu = GpuInfo::builder()
        .vendor(Vendor::Nvidia)
        .name("Test GPU")
        .temperature(70.0)
        .utilization(50.0)
        .power_usage(200.0)
        .core_clock(1800)
        .memory_util(40.0)
        .memory_clock(7000)
        .power_limit(250.0)
        .memory_total(8)
        .max_clock_speed(2000)
        .driver_version("500.00")
        .active(true)
        .build();

    // format_* methods should return the same values as getters with unwrap_or
    assert_eq!(gpu.format_temperature(), gpu.temperature().unwrap_or(0.0));
    assert_eq!(gpu.format_utilization(), gpu.utilization().unwrap_or(0.0));
    assert_eq!(gpu.format_power_usage(), gpu.power_usage().unwrap_or(0.0));
    assert_eq!(gpu.format_core_clock(), gpu.core_clock().unwrap_or(0));
    assert_eq!(gpu.format_memory_util(), gpu.memory_util().unwrap_or(0.0));
    assert_eq!(gpu.format_memory_clock(), gpu.memory_clock().unwrap_or(0));
    assert_eq!(gpu.format_power_limit(), gpu.power_limit().unwrap_or(0.0));
    assert_eq!(gpu.format_memory_total(), gpu.memory_total().unwrap_or(0));
    assert_eq!(
        gpu.format_max_clock_speed(),
        gpu.max_clock_speed().unwrap_or(0)
    );
    assert_eq!(
        gpu.format_name_gpu(),
        gpu.name_gpu().unwrap_or("Unknown GPU")
    );
    assert_eq!(
        gpu.format_driver_version(),
        gpu.driver_version().unwrap_or("Unknown Driver Version")
    );
}
