//! Tests for format_* methods generated by impl_format_numeric! and impl_format_string! macros.
//!
//! These tests verify that the macro-generated methods work correctly with real GpuInfo instances.

use crate::vendor::Vendor;
use crate::GpuInfo;

/// Test format methods with all fields set to None (unknown GPU)
#[test]
fn test_format_methods_with_unknown_gpu() {
    let gpu = GpuInfo::unknown();
    assert_eq!(gpu.format_temperature(), "Not supported");
    assert_eq!(gpu.format_power_usage(), "Not supported");
    assert_eq!(gpu.format_power_limit(), "Not supported");
    assert_eq!(gpu.format_utilization(), "N/A");
    assert_eq!(gpu.format_memory_util(), "N/A");
    assert_eq!(gpu.format_core_clock(), "N/A");
    assert_eq!(gpu.format_memory_clock(), "N/A");
    assert_eq!(gpu.format_memory_total(), "N/A");
    assert_eq!(gpu.format_memory_used(), "N/A");
    assert_eq!(gpu.format_max_clock_speed(), "N/A");
    assert_eq!(gpu.format_name_gpu(), "Unknown GPU");
    assert_eq!(gpu.format_driver_version(), "Unknown Driver Version");
    assert_eq!(gpu.format_active(), "Inactive");
}

/// Test format methods with all fields populated
#[test]
fn test_format_methods_with_populated_gpu() {
    let gpu = GpuInfo::builder()
        .vendor(Vendor::Nvidia)
        .name("NVIDIA GeForce RTX 4090")
        .temperature(65.5)
        .utilization(85.0)
        .power_usage(350.0)
        .core_clock(2520)
        .memory_util(45.5)
        .memory_clock(10501)
        .power_limit(450.0)
        .memory_total(24576)
        .memory_used(12288)
        .max_clock_speed(2610)
        .driver_version("545.92")
        .active(true)
        .build();

    assert_eq!(gpu.format_temperature(), "65.50°C");
    assert_eq!(gpu.format_utilization(), "85.00%");
    assert_eq!(gpu.format_power_usage(), "350.00W");
    assert_eq!(gpu.format_memory_util(), "45.50%");
    assert_eq!(gpu.format_power_limit(), "450.00W");
    assert_eq!(gpu.format_core_clock(), "2520 MHz");
    assert_eq!(gpu.format_memory_clock(), "10501 MHz");
    assert_eq!(gpu.format_memory_total(), "24.00 GB");
    assert_eq!(gpu.format_memory_used(), "12.00 GB");
    assert_eq!(gpu.format_max_clock_speed(), "2610 MHz");
    assert_eq!(gpu.format_name_gpu(), "NVIDIA GeForce RTX 4090");
    assert_eq!(gpu.format_driver_version(), "545.92");
    assert_eq!(gpu.format_active(), "Active");
}

/// Test format methods with partial data (some fields None, some populated)
#[test]
fn test_format_methods_with_partial_data() {
    let gpu = GpuInfo::builder()
        .vendor(Vendor::Amd)
        .name("AMD Radeon RX 7900 XTX")
        .temperature(72.0)
        .power_usage(300.0)
        .memory_util(60.0)
        .active(false)
        .build();

    assert_eq!(gpu.format_name_gpu(), "AMD Radeon RX 7900 XTX");
    assert_eq!(gpu.format_temperature(), "72.00°C");
    assert_eq!(gpu.format_power_usage(), "300.00W");
    assert_eq!(gpu.format_memory_util(), "60.00%");
    assert_eq!(gpu.format_utilization(), "N/A");
    assert_eq!(gpu.format_core_clock(), "N/A");
    assert_eq!(gpu.format_memory_clock(), "N/A");
    assert_eq!(gpu.format_memory_total(), "N/A");
    assert_eq!(gpu.format_max_clock_speed(), "N/A");
    assert_eq!(gpu.format_power_limit(), "Not supported");
    assert_eq!(gpu.format_driver_version(), "Unknown Driver Version");
    assert_eq!(gpu.format_active(), "Inactive");
}

/// Test format_active with different states
#[test]
fn test_format_active_states() {
    let gpu_active = GpuInfo::builder().active(true).build();
    assert_eq!(gpu_active.format_active(), "Active");
    let gpu_inactive = GpuInfo::builder().active(false).build();
    assert_eq!(gpu_inactive.format_active(), "Inactive");
    let gpu_unknown = GpuInfo::unknown();
    assert_eq!(gpu_unknown.format_active(), "Inactive");
}

/// Test format methods with edge case values
#[test]
fn test_format_methods_edge_cases() {
    let gpu_zeros = GpuInfo::builder()
        .temperature(0.0)
        .utilization(0.0)
        .power_usage(0.0)
        .core_clock(0)
        .memory_clock(0)
        .memory_total(0)
        .build();

    assert_eq!(gpu_zeros.format_temperature(), "0.00°C");
    assert_eq!(gpu_zeros.format_utilization(), "0.00%");
    assert_eq!(gpu_zeros.format_power_usage(), "0.00W");
    assert_eq!(gpu_zeros.format_core_clock(), "0 MHz");
    assert_eq!(gpu_zeros.format_memory_clock(), "0 MHz");
    assert_eq!(gpu_zeros.format_memory_total(), "0.00 GB");
    let gpu_max = GpuInfo::builder()
        .temperature(100.0)
        .utilization(100.0)
        .power_usage(1000.0)
        .core_clock(5000)
        .memory_clock(20000)
        .memory_total(131072)
        .max_clock_speed(5000)
        .power_limit(1000.0)
        .build();

    assert_eq!(gpu_max.format_temperature(), "100.00°C");
    assert_eq!(gpu_max.format_utilization(), "100.00%");
    assert_eq!(gpu_max.format_power_usage(), "1000.00W");
    assert_eq!(gpu_max.format_core_clock(), "5000 MHz");
    assert_eq!(gpu_max.format_memory_clock(), "20000 MHz");
    assert_eq!(gpu_max.format_memory_total(), "128.00 GB");
    assert_eq!(gpu_max.format_max_clock_speed(), "5000 MHz");
    assert_eq!(gpu_max.format_power_limit(), "1000.00W");
}

/// Test format methods with empty string values
#[test]
fn test_format_methods_empty_strings() {
    let gpu = GpuInfo::builder().name("").driver_version("").build();
    assert_eq!(gpu.format_name_gpu(), "");
    assert_eq!(gpu.format_driver_version(), "");
}

/// Test format methods with special characters in strings
#[test]
fn test_format_methods_special_characters() {
    let gpu = GpuInfo::builder()
        .name("NVIDIA GeForce RTX 4090 (TM)")
        .driver_version("545.92.01-beta")
        .build();

    assert_eq!(gpu.format_name_gpu(), "NVIDIA GeForce RTX 4090 (TM)");
    assert_eq!(gpu.format_driver_version(), "545.92.01-beta");
}

/// Test format methods with floating point precision
#[test]
fn test_format_methods_float_precision() {
    let gpu = GpuInfo::builder()
        .temperature(65.123)
        .utilization(99.999)
        .power_usage(350.5)
        .memory_util(45.123)
        .power_limit(450.0)
        .build();

    assert_eq!(gpu.format_temperature(), "65.12°C"); // 65.123 -> 65.12
    assert_eq!(gpu.format_utilization(), "100.00%"); // 99.999 -> 100.0
    assert_eq!(gpu.format_power_usage(), "350.50W"); // 350.5 -> 350.50
    assert_eq!(gpu.format_memory_util(), "45.12%"); // 45.123 -> 45.12
    assert_eq!(gpu.format_power_limit(), "450.00W"); // 450.0 -> 450.00
}

/// Test that format methods work correctly with Intel GPU type
#[test]
fn test_format_methods_intel_gpu() {
    use crate::vendor::IntelGpuType;

    let gpu = GpuInfo::builder()
        .vendor(Vendor::Intel(IntelGpuType::Integrated))
        .name("Intel UHD Graphics 770")
        .temperature(55.0)
        .utilization(30.0)
        .memory_total(1024)
        .driver_version("31.0.101.4502")
        .active(true)
        .build();

    assert_eq!(gpu.format_name_gpu(), "Intel UHD Graphics 770");
    assert_eq!(gpu.format_temperature(), "55.00°C");
    assert_eq!(gpu.format_utilization(), "30.00%");
    assert_eq!(gpu.format_memory_total(), "1.00 GB");
    assert_eq!(gpu.format_driver_version(), "31.0.101.4502");
    assert_eq!(gpu.format_active(), "Active");
}

/// Test format methods consistency with getter methods
#[test]
fn test_format_methods_consistency_with_getters() {
    let gpu = GpuInfo::builder()
        .vendor(Vendor::Nvidia)
        .name("Test GPU")
        .temperature(70.0)
        .utilization(50.0)
        .power_usage(200.0)
        .core_clock(1800)
        .memory_util(40.0)
        .memory_clock(7000)
        .power_limit(250.0)
        .memory_total(8)
        .max_clock_speed(2000)
        .driver_version("500.00")
        .active(true)
        .build();

    assert_eq!(gpu.format_temperature(), "70.00°C");
    assert_eq!(gpu.format_utilization(), "50.00%");
    assert_eq!(gpu.format_power_usage(), "200.00W");
    assert_eq!(gpu.format_core_clock(), "1800 MHz");
    assert_eq!(gpu.format_memory_util(), "40.00%");
    assert_eq!(gpu.format_memory_clock(), "7000 MHz");
    assert_eq!(gpu.format_power_limit(), "250.00W");
    assert_eq!(gpu.format_memory_total(), "0.01 GB");
    assert_eq!(gpu.format_max_clock_speed(), "2000 MHz");
    assert_eq!(gpu.format_name_gpu(), "Test GPU");
    assert_eq!(gpu.format_driver_version(), "500.00");
}
